import {
  CalendarDays,
  ChartNoAxesCombined,
  ClipboardPlus,
  Home,
  MessagesSquare,
  Settings2,
  UsersRound,
  WalletCards,
} from 'lucide-react'
export const modules = [
  {
    path: '/',
    label: 'Inicio',
    icon: Home,
    group: 'Consultorio',
    phase: 0,
    description: 'Tu espacio de trabajo.',
  },
  {
    path: '/agenda',
    label: 'Agenda',
    icon: CalendarDays,
    group: 'Consultorio',
    phase: 2,
    description: 'Organiza las citas y la disponibilidad de cada odontólogo.',
    empty: 'Tu agenda comienza aquí',
    detail:
      'Las citas manuales y las reservas por WhatsApp comparten las reglas de disponibilidad y la duración completa del servicio.',
  },
  {
    path: '/pacientes',
    label: 'Pacientes',
    icon: UsersRound,
    group: 'Consultorio',
    phase: 2,
    description: 'Toda la información del paciente, en un solo lugar.',
    empty: 'Cada paciente, una historia',
    detail:
      'Fichas, contactos y responsables de menores, con acceso a las citas, atenciones y cuentas del paciente.',
  },
  {
    path: '/clinica',
    label: 'Historia clínica',
    icon: ClipboardPlus,
    group: 'Consultorio',
    phase: 3,
    description: 'Acompaña la evolución clínica con información organizada.',
    empty: 'Un registro para cada atención',
    detail:
      'Atenciones, odontograma y documentos en la ficha del paciente, con historial de cambios.',
  },
  {
    path: '/tratamientos',
    label: 'Presupuestos y planes',
    icon: ClipboardPlus,
    group: 'Gestión',
    phase: 4,
    description: 'Acuerdos y avance de tratamientos.',
    empty: 'Acuerdos claros',
    detail: 'Presupuestos, planes y sesiones con importes conservados.',
  },
  {
    path: '/finanzas',
    label: 'Finanzas',
    icon: WalletCards,
    group: 'Gestión',
    phase: 4,
    description: 'Cobros, cuotas y saldos con claridad.',
    empty: 'Cuentas claras, mejor seguimiento',
    detail: 'Cargos por servicios realizados y planes aceptados. Abonos y cuotas con trazabilidad.',
  },
  {
    path: '/conversaciones',
    label: 'WhatsApp',
    icon: MessagesSquare,
    group: 'Gestión',
    phase: 6,
    description: 'Reservas y conversaciones conectadas con tu agenda.',
    empty: 'La próxima cita empieza con un mensaje',
    detail:
      'El asistente consulta horarios y registra reservas después de la confirmación del paciente, con historial verificable.',
  },
  {
    path: '/reportes',
    label: 'Reportes',
    icon: ChartNoAxesCombined,
    group: 'Gestión',
    phase: 8,
    description: 'Una visión clara de la actividad del consultorio.',
    empty: 'Información para decidir mejor',
    detail: 'Actividad del consultorio por periodo.',
  },
  {
    path: '/configuracion',
    label: 'Configuración',
    icon: Settings2,
    group: 'Sistema',
    phase: 1,
    description: 'Un sistema que se adapta a tu consultorio.',
    empty: 'Tu consultorio, a tu manera',
    detail: 'Identidad, usuarios, odontólogos, servicios y horarios de tu consultorio.',
  },
] as const
export type Module = (typeof modules)[number]
export const navigationGroups = ['Consultorio', 'Gestión', 'Sistema'] as const
